### PR TITLE
libdlb-demo: Use /pf and /vf instead of /dlb

### PR DESCRIPTION
**Pull request by hj-johannes-lee**
Signed-off-by: Hyeongju Johannes Lee <hyeongju.lee@intel.com>

### CODE REVIEW

**Comment by bart0sh** [comment]
@hj-johannes-lee I'd suggest to move this into https://github.com/bart0sh/intel-device-plugins-for-kubernetes/pull/8 as it strictly depends on that implementation.

**Comment by hj-johannes-lee** [comment]
> @hj-johannes-lee I'd suggest to move this into #8 as it strictly depends on that implementation.

Ok.! At first, I was thinking to do so. But, then the number of commits may not be kept one any more, right?

**Comment by bart0sh** [comment]
That's ok to have it in the same commit. It's a small change, so the commit content would be perfectly readable.

**Comment by bart0sh** [comment]
Anyway I'll squash it into the existing commit after the merge.

**Comment by hj-johannes-lee** [comment]
OK, since I put the yaml file change in another commit and pr, I close this pr.!

**Pull request closed without merging**
